import { ScreenerCriteria } from '../types';

export const COLORS = {
  background: '#0a0e1a',
  surface: '#141927',
  surfaceAlt: '#1a2035',
  border: '#252d42',
  primary: '#00d4aa',
  primaryDark: '#00a882',
  buy: '#00d4aa',
  sell: '#ff4757',
  text: '#e8eaf0',
  textSecondary: '#8892a4',
  textMuted: '#4a5568',
  positive: '#00d4aa',
  negative: '#ff4757',
};

export const BACKGROUND_FETCH_TASK = 'nasduck-daily-scan';
export const FINNHUB_BASE_URL = 'https://finnhub.io/api/v1';

// Scan universe filters applied during scanning
export const UNIVERSE_MIN_PRICE = 5;       // USD
export const UNIVERSE_MIN_VOLUME = 500000; // shares/day avg
export const RATE_LIMIT_MS = 1200;         // ms between API calls (50/min)

// Default minimum absolute price change % — filters flat/boring stocks
export const DEFAULT_MIN_CHANGE_PCT = 1.0;


/**
 * Scoring weights per criteria id.
 * Higher = stronger / more independent signal. Default = 1.
 */
export const CRITERIA_WEIGHTS: Record<string, number> = {
  volume_spike:            3,
  macd_crossover_up:       3,
  macd_crossover_down:     3,
  ema_crossover_up:        3,
  ema_crossover_down:      3,
  bollinger_breakout_up:   3,
  bollinger_breakout_down: 3,
  price_surge:             2,
  gap_up:                  2,
  gap_down:                2,
  new_52w_high:            2,
  new_52w_low:             2,
  rsi_oversold:            2,
  rsi_overbought:          2,
  atr_spike:               2,
  obv_trend_up:            2,
  obv_trend_down:          2,
  stoch_oversold:          2,
  stoch_overbought:        2,
  trending_up:             1,
  trending_down:           1,
  above_sma50:             1,
  below_sma50:             1,
  price_vs_ema_above:      1,
  price_vs_ema_below:      1,
  adx_strong:              1,
  inside_bar:              1,
  volume_dryup:            1,
  min_market_cap:          1,
};

export const DEFAULT_CRITERIA: ScreenerCriteria[] = [
  {
    id: 'trending_up',
    name: 'Trending Up',
    description: 'Price closes higher than previous day for N consecutive days',
    signal: 'buy',
    enabled: true,
    threshold: 3,
    thresholdLabel: 'Consecutive up days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'trending_down',
    name: 'Trending Down',
    description: 'Price closes lower than previous day for N consecutive days',
    signal: 'sell',
    enabled: true,
    threshold: 3,
    thresholdLabel: 'Consecutive down days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'rsi_oversold',
    name: 'RSI Oversold',
    description: 'RSI(14) drops below threshold — potential reversal upward',
    signal: 'buy',
    enabled: true,
    threshold: 30,
    thresholdLabel: 'RSI below',
    thresholdMin: 10,
    thresholdMax: 45,
    thresholdStep: 1,
  },
  {
    id: 'rsi_overbought',
    name: 'RSI Overbought',
    description: 'RSI(14) rises above threshold — potential reversal downward',
    signal: 'sell',
    enabled: true,
    threshold: 70,
    thresholdLabel: 'RSI above',
    thresholdMin: 55,
    thresholdMax: 90,
    thresholdStep: 1,
  },
  {
    id: 'above_sma50',
    name: 'Price Crossed Above SMA50',
    description: 'Today\'s price moved above the 50-day moving average',
    signal: 'buy',
    enabled: false,
    threshold: 50,
    thresholdLabel: 'SMA period',
    thresholdMin: 10,
    thresholdMax: 200,
    thresholdStep: 5,
    thresholdSuffix: ' days',
  },
  {
    id: 'below_sma50',
    name: 'Price Crossed Below SMA50',
    description: 'Today\'s price moved below the 50-day moving average',
    signal: 'sell',
    enabled: false,
    threshold: 50,
    thresholdLabel: 'SMA period',
    thresholdMin: 10,
    thresholdMax: 200,
    thresholdStep: 5,
    thresholdSuffix: ' days',
  },
  {
    id: 'volume_spike',
    name: 'Volume Spike',
    description: 'Today\'s volume exceeds N times the 20-day average',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Volume multiplier',
    thresholdMin: 1.5,
    thresholdMax: 10,
    thresholdStep: 0.5,
    thresholdSuffix: '×',
  },
  {
    id: 'new_52w_high',
    name: 'New 52-Week High',
    description: 'Price hits a new 52-week high today',
    signal: 'buy',
    enabled: false,
    threshold: 252,
    thresholdLabel: 'Trading days lookback',
    thresholdMin: 50,
    thresholdMax: 252,
    thresholdStep: 10,
    thresholdSuffix: ' days',
  },
  {
    id: 'new_52w_low',
    name: 'New 52-Week Low',
    description: 'Price hits a new 52-week low today',
    signal: 'sell',
    enabled: false,
    threshold: 252,
    thresholdLabel: 'Trading days lookback',
    thresholdMin: 50,
    thresholdMax: 252,
    thresholdStep: 10,
    thresholdSuffix: ' days',
  },
  // ── MACD ──────────────────────────────────────────────────
  {
    id: 'macd_crossover_up',
    name: 'MACD Crossover Up',
    description: 'MACD line crosses above signal line — momentum turning bullish',
    signal: 'buy',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Signal EMA period',
    thresholdMin: 3,
    thresholdMax: 20,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'macd_crossover_down',
    name: 'MACD Crossover Down',
    description: 'MACD line crosses below signal line — momentum turning bearish',
    signal: 'sell',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Signal EMA period',
    thresholdMin: 3,
    thresholdMax: 20,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  // ── EMA Crossover ─────────────────────────────────────────
  {
    id: 'ema_crossover_up',
    name: 'EMA Crossover Up',
    description: 'Short EMA crosses above long EMA — uptrend starting',
    signal: 'buy',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Short EMA',
    thresholdMin: 3,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 21,
    threshold2Label: 'Long EMA',
    threshold2Min: 10,
    threshold2Max: 200,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  {
    id: 'ema_crossover_down',
    name: 'EMA Crossover Down',
    description: 'Short EMA crosses below long EMA — downtrend starting',
    signal: 'sell',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Short EMA',
    thresholdMin: 3,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 21,
    threshold2Label: 'Long EMA',
    threshold2Min: 10,
    threshold2Max: 200,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Price vs EMA ──────────────────────────────────────────
  {
    id: 'price_vs_ema_above',
    name: 'Price Above EMA',
    description: 'Price is at least X% above its EMA — strong uptrend',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min % above EMA',
    thresholdMin: 0,
    thresholdMax: 20,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
    threshold2: 20,
    threshold2Label: 'EMA period',
    threshold2Min: 5,
    threshold2Max: 200,
    threshold2Step: 5,
    threshold2Suffix: ' days',
  },
  {
    id: 'price_vs_ema_below',
    name: 'Price Below EMA',
    description: 'Price is at least X% below its EMA — strong downtrend',
    signal: 'sell',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min % below EMA',
    thresholdMin: 0,
    thresholdMax: 20,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
    threshold2: 20,
    threshold2Label: 'EMA period',
    threshold2Min: 5,
    threshold2Max: 200,
    threshold2Step: 5,
    threshold2Suffix: ' days',
  },
  // ── Bollinger Bands ───────────────────────────────────────
  {
    id: 'bollinger_breakout_up',
    name: 'Bollinger Breakout Up',
    description: 'Price closes above upper Bollinger Band — strong momentum',
    signal: 'buy',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'BB period',
    thresholdMin: 5,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 2,
    threshold2Label: 'Std dev multiplier',
    threshold2Min: 1,
    threshold2Max: 3,
    threshold2Step: 0.5,
    threshold2Suffix: '×',
  },
  {
    id: 'bollinger_breakout_down',
    name: 'Bollinger Breakdown',
    description: 'Price closes below lower Bollinger Band — strong selling pressure',
    signal: 'sell',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'BB period',
    thresholdMin: 5,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 2,
    threshold2Label: 'Std dev multiplier',
    threshold2Min: 1,
    threshold2Max: 3,
    threshold2Step: 0.5,
    threshold2Suffix: '×',
  },
  // ── ATR Spike ─────────────────────────────────────────────
  {
    id: 'atr_spike',
    name: 'ATR Spike',
    description: 'True range is unusually large — big move / high volatility day',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'ATR multiplier',
    thresholdMin: 1.5,
    thresholdMax: 5,
    thresholdStep: 0.5,
    thresholdSuffix: '×',
    threshold2: 14,
    threshold2Label: 'ATR period',
    threshold2Min: 5,
    threshold2Max: 30,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Volume Dry-Up ─────────────────────────────────────────
  {
    id: 'volume_dryup',
    name: 'Volume Dry-Up',
    description: 'Volume drops to X% of average — consolidation before potential breakout',
    signal: 'buy',
    enabled: false,
    threshold: 40,
    thresholdLabel: 'Max % of avg volume',
    thresholdMin: 10,
    thresholdMax: 70,
    thresholdStep: 5,
    thresholdSuffix: '%',
  },
  // ── OBV Trend ─────────────────────────────────────────────
  {
    id: 'obv_trend_up',
    name: 'OBV Trending Up',
    description: 'On-Balance Volume rising for N consecutive days — buying pressure building',
    signal: 'buy',
    enabled: false,
    threshold: 3,
    thresholdLabel: 'Consecutive up days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'obv_trend_down',
    name: 'OBV Trending Down',
    description: 'On-Balance Volume falling for N consecutive days — selling pressure building',
    signal: 'sell',
    enabled: false,
    threshold: 3,
    thresholdLabel: 'Consecutive down days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  // ── Inside Bar ────────────────────────────────────────────
  {
    id: 'inside_bar',
    name: 'Inside Bar',
    description: "Today's range is inside yesterday's — consolidation, potential breakout setup",
    signal: 'buy',
    enabled: false,
    threshold: 0,
    thresholdLabel: 'Min prev bar range %',
    thresholdMin: 0,
    thresholdMax: 10,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  // ── Gap ───────────────────────────────────────────────────
  {
    id: 'gap_up',
    name: 'Gap Up',
    description: "Today's open is significantly above yesterday's close — strong opening momentum",
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min gap size',
    thresholdMin: 0.5,
    thresholdMax: 15,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  {
    id: 'gap_down',
    name: 'Gap Down',
    description: "Today's open is significantly below yesterday's close — strong opening sell-off",
    signal: 'sell',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min gap size',
    thresholdMin: 0.5,
    thresholdMax: 15,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  // ── Stochastic ────────────────────────────────────────────
  {
    id: 'stoch_oversold',
    name: 'Stochastic Oversold',
    description: '%K crosses above %D in oversold zone — potential reversal upward',
    signal: 'buy',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'Oversold level',
    thresholdMin: 10,
    thresholdMax: 35,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: '%K period',
    threshold2Min: 5,
    threshold2Max: 21,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  {
    id: 'stoch_overbought',
    name: 'Stochastic Overbought',
    description: '%K crosses below %D in overbought zone — potential reversal downward',
    signal: 'sell',
    enabled: false,
    threshold: 80,
    thresholdLabel: 'Overbought level',
    thresholdMin: 65,
    thresholdMax: 90,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: '%K period',
    threshold2Min: 5,
    threshold2Max: 21,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── ADX ───────────────────────────────────────────────────
  {
    id: 'adx_strong',
    name: 'ADX Strong Trend',
    description: 'ADX above threshold — strong trend in either direction (use with other criteria)',
    signal: 'buy',
    enabled: false,
    threshold: 25,
    thresholdLabel: 'Min ADX value',
    thresholdMin: 15,
    thresholdMax: 50,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: 'ADX period',
    threshold2Min: 7,
    threshold2Max: 28,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Min Market Cap ────────────────────────────────────────
  {
    id: 'min_market_cap',
    name: 'Min Market Cap',
    description: 'Only include stocks with market cap above this threshold (fetched from Finnhub)',
    signal: 'buy' as const,
    enabled: false,
    threshold: 0.3,
    thresholdLabel: 'Min market cap',
    thresholdMin: 0.1,
    thresholdMax: 500,
    thresholdStep: 0.1,
    thresholdSuffix: 'B',
  },
  // ── Price Surge ───────────────────────────────────────────
  {
    id: 'price_surge',
    name: 'Price Surge',
    description: 'Price increased by at least X% over the last N days',
    signal: 'buy',
    enabled: true,
    threshold: 10,
    thresholdLabel: 'Min gain',
    thresholdMin: 1,
    thresholdMax: 100,
    thresholdStep: 1,
    thresholdSuffix: '%',
    threshold2: 5,
    threshold2Label: 'Over period',
    threshold2Min: 1,
    threshold2Max: 60,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
];
