import { ScreenerCriteria } from '../types';

export const COLORS = {
  background: '#0a0e1a',
  surface: '#141927',
  surfaceAlt: '#1a2035',
  border: '#252d42',
  primary: '#00d4aa',
  primaryDark: '#00a882',
  buy: '#00d4aa',
  sell: '#ff4757',
  text: '#e8eaf0',
  textSecondary: '#8892a4',
  textMuted: '#4a5568',
  positive: '#00d4aa',
  negative: '#ff4757',
};

export const BACKGROUND_FETCH_TASK = 'nasduck-daily-scan';
export const FINNHUB_BASE_URL = 'https://finnhub.io/api/v1';

// Cloud scan server — deploy nasduck-server once, all users share it
// Replace with your Railway/Render URL after deploying
export const CLOUD_SERVER_URL = 'https://nusduck-server.onrender.com';

// Scan universe filters applied during scanning
export const UNIVERSE_MIN_PRICE = 5;       // USD
export const UNIVERSE_MIN_VOLUME = 500000; // shares/day avg
export const RATE_LIMIT_MS = 1200;         // ms between API calls (50/min)

// Daily auto-scan is blocked locally above this. At ~1.5s/stock, 1000 stocks
// ≈ 25 min — anything bigger should run via Cloud Scan instead.
export const LOCAL_SCAN_MAX_STOCKS = 1000;

// Default minimum absolute price change % — filters flat/boring stocks
export const DEFAULT_MIN_CHANGE_PCT = 1.0;


/**
 * Scoring weights per criteria id.
 * Higher = stronger / more independent signal. Default = 1.
 */
export const CRITERIA_WEIGHTS: Record<string, number> = {
  volume_spike:            3,
  macd_crossover_up:       3,
  macd_crossover_down:     3,
  ema_crossover_up:        3,
  ema_crossover_down:      3,
  bollinger_breakout_up:   3,
  bollinger_breakout_down: 3,
  price_surge:             2,
  gap_up:                  2,
  gap_down:                2,
  new_52w_high:            2,
  new_52w_low:             2,
  rsi_oversold:            2,
  rsi_overbought:          2,
  atr_spike:               2,
  obv_trend_up:            2,
  obv_trend_down:          2,
  stoch_oversold:          2,
  stoch_overbought:        2,
  trending_up:             1,
  trending_down:           1,
  above_sma50:             1,
  below_sma50:             1,
  price_vs_ema_above:      1,
  price_vs_ema_below:      1,
  adx_strong:              1,
  inside_bar:              1,
  volume_dryup:            1,
  put_call_ratio_low:      3,
  put_call_ratio_high:     3,
  high_iv:                 2,
  near_max_pain:           2,
};

export const DEFAULT_CRITERIA: ScreenerCriteria[] = [
  {
    id: 'trending_up',
    name: 'Trending Up',
    description: 'Flags stocks whose closing price has been higher than the prior day for N consecutive sessions. A simple but reliable sign of sustained buying pressure and short-term price momentum. Longer streaks indicate a stronger, more established uptrend.',
    signal: 'buy',
    enabled: true,
    threshold: 3,
    thresholdLabel: 'Consecutive up days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'trending_down',
    name: 'Trending Down',
    description: 'Flags portfolio stocks whose closing price has been lower than the prior day for N consecutive sessions, indicating persistent selling pressure. A prolonged downtrend often accelerates, making it a useful early warning to review or exit a position.',
    signal: 'sell',
    enabled: true,
    threshold: 3,
    thresholdLabel: 'Consecutive down days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'rsi_oversold',
    name: 'RSI Oversold',
    description: 'RSI (Relative Strength Index) is a momentum oscillator that measures the speed and magnitude of recent price changes on a scale of 0 to 100. A reading below 30 indicates the stock is oversold — it has declined sharply in a short period and selling momentum may be exhausted. This level is traditionally associated with potential price reversals or bounces. The threshold setting controls how low RSI must drop before triggering.',
    signal: 'buy',
    enabled: true,
    threshold: 30,
    thresholdLabel: 'RSI below',
    thresholdMin: 10,
    thresholdMax: 45,
    thresholdStep: 1,
  },
  {
    id: 'rsi_overbought',
    name: 'RSI Overbought',
    description: 'RSI (Relative Strength Index) above 70 signals the stock is overbought — it has rallied rapidly and buying momentum may be overextended. While a stock can remain overbought during strong trends, this reading increases the probability of a pullback or reversal, making it a useful sell alert for portfolio holdings.',
    signal: 'sell',
    enabled: true,
    threshold: 70,
    thresholdLabel: 'RSI above',
    thresholdMin: 55,
    thresholdMax: 90,
    thresholdStep: 1,
  },
  {
    id: 'above_sma50',
    name: 'Price Crossed Above SMA50',
    description: 'SMA (Simple Moving Average) is the plain average of closing prices over a set number of days. A crossover above the SMA signals a shift from weakness to strength — the stock\'s current price is now outpacing its recent average, suggesting improved momentum. The 50-day SMA is one of the most widely watched trendlines by institutional traders.',
    signal: 'buy',
    enabled: false,
    threshold: 50,
    thresholdLabel: 'SMA period',
    thresholdMin: 10,
    thresholdMax: 200,
    thresholdStep: 5,
    thresholdSuffix: ' days',
  },
  {
    id: 'below_sma50',
    name: 'Price Crossed Below SMA50',
    description: 'A crossover below the SMA (Simple Moving Average) signals deteriorating momentum — the current price has fallen below the stock\'s recent average, meaning recent sellers are outpacing buyers. This is often an early warning of a deeper downtrend, particularly when it occurs on elevated volume.',
    signal: 'sell',
    enabled: false,
    threshold: 50,
    thresholdLabel: 'SMA period',
    thresholdMin: 10,
    thresholdMax: 200,
    thresholdStep: 5,
    thresholdSuffix: ' days',
  },
  {
    id: 'volume_spike',
    name: 'Volume Spike',
    description: 'Volume measures the number of shares traded in a session. A volume spike — where today\'s volume significantly exceeds the 20-day average — signals unusual market interest, often driven by earnings, news, or institutional activity. High volume validates a price move; a spike on an up day is a strong bullish confirmation, while a spike on a down day may indicate distribution.',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Volume multiplier',
    thresholdMin: 1.5,
    thresholdMax: 10,
    thresholdStep: 0.5,
    thresholdSuffix: '×',
  },
  {
    id: 'new_52w_high',
    name: 'New 52-Week High',
    description: 'Triggers when a stock closes at its highest price over the past year (approximately 252 trading days). New 52-week highs indicate strong price discovery with no overhead resistance — all prior buyers are in profit and there is no selling pressure from investors waiting to break even. Historically, stocks breaking to new annual highs tend to continue outperforming.',
    signal: 'buy',
    enabled: false,
    threshold: 252,
    thresholdLabel: 'Trading days lookback',
    thresholdMin: 50,
    thresholdMax: 252,
    thresholdStep: 10,
    thresholdSuffix: ' days',
  },
  {
    id: 'new_52w_low',
    name: 'New 52-Week Low',
    description: 'Triggers when a stock closes at its lowest price over the past year. A new 52-week low signals that every investor who bought in the last year is sitting at a loss, creating persistent overhead selling pressure as those holders look to exit at breakeven. This is a high-conviction sell signal for portfolio positions.',
    signal: 'sell',
    enabled: false,
    threshold: 252,
    thresholdLabel: 'Trading days lookback',
    thresholdMin: 50,
    thresholdMax: 252,
    thresholdStep: 10,
    thresholdSuffix: ' days',
  },
  // ── MACD ──────────────────────────────────────────────────
  {
    id: 'macd_crossover_up',
    name: 'MACD Crossover Up',
    description: 'MACD (Moving Average Convergence Divergence) is a momentum indicator calculated as the difference between a 12-day and 26-day EMA. It is plotted alongside a 9-day signal line. A bullish crossover occurs when the MACD line crosses above the signal line, indicating that short-term momentum is accelerating faster than the medium-term trend — a widely-used entry signal. The signal period setting controls the smoothing of the trigger line.',
    signal: 'buy',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Signal EMA period',
    thresholdMin: 3,
    thresholdMax: 20,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'macd_crossover_down',
    name: 'MACD Crossover Down',
    description: 'MACD (Moving Average Convergence Divergence) crossing below its signal line indicates that short-term momentum is decelerating relative to the medium-term trend. This bearish crossover is one of the most commonly used sell signals in technical analysis and often precedes a sustained price decline, particularly when confirmed by rising volume.',
    signal: 'sell',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Signal EMA period',
    thresholdMin: 3,
    thresholdMax: 20,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  // ── EMA Crossover ─────────────────────────────────────────
  {
    id: 'ema_crossover_up',
    name: 'EMA Crossover Up',
    description: 'EMA (Exponential Moving Average) is a moving average that gives more weight to recent prices, making it more responsive than a simple average. A bullish crossover occurs when a shorter-period EMA crosses above a longer-period EMA — e.g. the 9-day crossing above the 21-day. This indicates that recent price action is strengthening relative to the broader trend, a classic early signal of a new uptrend.',
    signal: 'buy',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Short EMA',
    thresholdMin: 3,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 21,
    threshold2Label: 'Long EMA',
    threshold2Min: 10,
    threshold2Max: 200,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  {
    id: 'ema_crossover_down',
    name: 'EMA Crossover Down',
    description: 'A bearish EMA (Exponential Moving Average) crossover occurs when a shorter-period EMA crosses below a longer-period EMA — indicating that recent price momentum has weakened below the broader trend. This is often referred to as a "death cross" on longer timeframes and signals that selling pressure is gaining the upper hand.',
    signal: 'sell',
    enabled: false,
    threshold: 9,
    thresholdLabel: 'Short EMA',
    thresholdMin: 3,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 21,
    threshold2Label: 'Long EMA',
    threshold2Min: 10,
    threshold2Max: 200,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Price vs EMA ──────────────────────────────────────────
  {
    id: 'price_vs_ema_above',
    name: 'Price Above EMA',
    description: 'Triggers when the current price is trading a set percentage above its EMA (Exponential Moving Average). Rather than just crossing the average, this requires the price to be meaningfully extended above it — confirming a strong, established uptrend. Useful for finding stocks with genuine momentum rather than borderline crossovers.',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min % above EMA',
    thresholdMin: 0,
    thresholdMax: 20,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
    threshold2: 20,
    threshold2Label: 'EMA period',
    threshold2Min: 5,
    threshold2Max: 200,
    threshold2Step: 5,
    threshold2Suffix: ' days',
  },
  {
    id: 'price_vs_ema_below',
    name: 'Price Below EMA',
    description: 'Triggers when the current price is trading a set percentage below its EMA (Exponential Moving Average). A stock persistently below its moving average signals that sellers are firmly in control. The EMA period setting adjusts whether you\'re tracking short-term or longer-term trend deterioration.',
    signal: 'sell',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min % below EMA',
    thresholdMin: 0,
    thresholdMax: 20,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
    threshold2: 20,
    threshold2Label: 'EMA period',
    threshold2Min: 5,
    threshold2Max: 200,
    threshold2Step: 5,
    threshold2Suffix: ' days',
  },
  // ── Bollinger Bands ───────────────────────────────────────
  {
    id: 'bollinger_breakout_up',
    name: 'Bollinger Breakout Up',
    description: 'Bollinger Bands are envelope lines plotted above and below a moving average, set at a defined number of standard deviations. They adapt to volatility — widening when the stock is volatile and narrowing when it is calm. A close above the upper band means the price has broken out of its normal range, signaling unusually strong buying momentum. The period setting controls the moving average length; the standard deviation multiplier controls how wide the bands are.',
    signal: 'buy',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'BB period',
    thresholdMin: 5,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 2,
    threshold2Label: 'Std dev multiplier',
    threshold2Min: 1,
    threshold2Max: 3,
    threshold2Step: 0.5,
    threshold2Suffix: '×',
  },
  {
    id: 'bollinger_breakout_down',
    name: 'Bollinger Breakdown',
    description: 'A close below the lower Bollinger Band means the price has fallen outside its statistically normal range, indicating unusually strong selling pressure. While this can occasionally mark a short-term oversold extreme, during downtrends it often signals accelerating weakness and further decline ahead.',
    signal: 'sell',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'BB period',
    thresholdMin: 5,
    thresholdMax: 50,
    thresholdStep: 1,
    thresholdSuffix: ' days',
    threshold2: 2,
    threshold2Label: 'Std dev multiplier',
    threshold2Min: 1,
    threshold2Max: 3,
    threshold2Step: 0.5,
    threshold2Suffix: '×',
  },
  // ── ATR Spike ─────────────────────────────────────────────
  {
    id: 'atr_spike',
    name: 'ATR Spike',
    description: 'ATR (Average True Range) measures daily price volatility by calculating the average of each session\'s full range — including any gap from the prior close. An ATR spike means today\'s price swing is significantly larger than the recent norm, indicating a surge in activity. This can precede major breakouts or breakdowns and is useful for identifying stocks entering a high-conviction move.',
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'ATR multiplier',
    thresholdMin: 1.5,
    thresholdMax: 5,
    thresholdStep: 0.5,
    thresholdSuffix: '×',
    threshold2: 14,
    threshold2Label: 'ATR period',
    threshold2Min: 5,
    threshold2Max: 30,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Volume Dry-Up ─────────────────────────────────────────
  {
    id: 'volume_dryup',
    name: 'Volume Dry-Up',
    description: 'A volume dry-up occurs when trading activity drops sharply below the recent average — indicating that both buyers and sellers have temporarily stepped back. This low-activity consolidation often precedes a significant directional move, as the next wave of buying or selling tends to be decisive. Best used in combination with price near a key support or resistance level.',
    signal: 'buy',
    enabled: false,
    threshold: 40,
    thresholdLabel: 'Max % of avg volume',
    thresholdMin: 10,
    thresholdMax: 70,
    thresholdStep: 5,
    thresholdSuffix: '%',
  },
  // ── OBV Trend ─────────────────────────────────────────────
  {
    id: 'obv_trend_up',
    name: 'OBV Trending Up',
    description: 'OBV (On-Balance Volume) is a cumulative indicator that adds volume on up days and subtracts it on down days. It tracks whether volume is flowing into or out of a stock. When OBV rises for several consecutive days, it means more volume is consistently accompanying price gains — a sign that institutional buying is quietly accumulating the stock, often before a larger price move.',
    signal: 'buy',
    enabled: false,
    threshold: 3,
    thresholdLabel: 'Consecutive up days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  {
    id: 'obv_trend_down',
    name: 'OBV Trending Down',
    description: 'OBV (On-Balance Volume) falling for consecutive days indicates that higher volume is consistently accompanying price declines — a sign of distribution, where larger players are quietly exiting positions. Declining OBV can precede visible price weakness and is often used as an early warning before the chart itself looks obviously bearish.',
    signal: 'sell',
    enabled: false,
    threshold: 3,
    thresholdLabel: 'Consecutive down days',
    thresholdMin: 2,
    thresholdMax: 10,
    thresholdStep: 1,
    thresholdSuffix: ' days',
  },
  // ── Inside Bar ────────────────────────────────────────────
  {
    id: 'inside_bar',
    name: 'Inside Bar',
    description: "An inside bar forms when today's high and low are both within yesterday's range — meaning the market moved less than the day before. It signals a pause or consolidation after a prior move, where neither buyers nor sellers gained ground. Inside bars are often followed by a sharp directional breakout as the compressed energy is released.",
    signal: 'buy',
    enabled: false,
    threshold: 0,
    thresholdLabel: 'Min prev bar range %',
    thresholdMin: 0,
    thresholdMax: 10,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  // ── Gap ───────────────────────────────────────────────────
  {
    id: 'gap_up',
    name: 'Gap Up',
    description: "A gap up occurs when today's opening price is notably higher than yesterday's closing price, leaving a blank space on the chart. This typically results from overnight news, earnings beats, or analyst upgrades. Gap ups signal strong pre-market demand and often indicate institutional conviction in the stock's near-term direction.",
    signal: 'buy',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min gap size',
    thresholdMin: 0.5,
    thresholdMax: 15,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  {
    id: 'gap_down',
    name: 'Gap Down',
    description: "A gap down occurs when today's opening price is notably lower than yesterday's closing price. This typically follows negative news, earnings misses, or broader market selling. Gap downs signal strong pre-market selling pressure and are a high-priority alert for portfolio stocks that may be entering a sharp decline.",
    signal: 'sell',
    enabled: false,
    threshold: 2,
    thresholdLabel: 'Min gap size',
    thresholdMin: 0.5,
    thresholdMax: 15,
    thresholdStep: 0.5,
    thresholdSuffix: '%',
  },
  // ── Stochastic ────────────────────────────────────────────
  {
    id: 'stoch_oversold',
    name: 'Stochastic Oversold',
    description: 'The Stochastic Oscillator compares a stock\'s closing price to its price range over a set period, producing two lines: %K (the fast line) and %D (a smoothed signal line), both on a 0–100 scale. When %K crosses above %D while both are in the oversold zone (below 20), it signals that recent selling momentum is fading and a potential reversal upward may be underway. The oversold level and %K period are both adjustable.',
    signal: 'buy',
    enabled: false,
    threshold: 20,
    thresholdLabel: 'Oversold level',
    thresholdMin: 10,
    thresholdMax: 35,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: '%K period',
    threshold2Min: 5,
    threshold2Max: 21,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  {
    id: 'stoch_overbought',
    name: 'Stochastic Overbought',
    description: 'When the Stochastic %K line crosses below the %D signal line while both are in the overbought zone (above 80), it signals that recent buying momentum is exhausting itself and a potential reversal downward may follow. The overbought level threshold and %K period are both adjustable to suit different sensitivity preferences.',
    signal: 'sell',
    enabled: false,
    threshold: 80,
    thresholdLabel: 'Overbought level',
    thresholdMin: 65,
    thresholdMax: 90,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: '%K period',
    threshold2Min: 5,
    threshold2Max: 21,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── ADX ───────────────────────────────────────────────────
  {
    id: 'adx_strong',
    name: 'ADX Strong Trend',
    description: 'ADX (Average Directional Index) measures the strength of a trend regardless of its direction — it tells you how strongly a stock is trending, not whether it\'s going up or down. A reading above 25 indicates a strong, established trend; above 40 signals a very strong trend. ADX is best used alongside directional criteria (e.g. Trending Up or MACD) to confirm that a detected move has real momentum behind it.',
    signal: 'buy',
    enabled: false,
    threshold: 25,
    thresholdLabel: 'Min ADX value',
    thresholdMin: 15,
    thresholdMax: 50,
    thresholdStep: 5,
    threshold2: 14,
    threshold2Label: 'ADX period',
    threshold2Min: 7,
    threshold2Max: 28,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Price Surge ───────────────────────────────────────────
  {
    id: 'price_surge',
    name: 'Price Surge',
    description: 'Triggers when the stock has gained at least a specified percentage over a defined lookback period. Unlike single-day momentum, a price surge measures sustained multi-day appreciation — useful for identifying stocks in the early or mid-stage of a strong move. The minimum gain and period settings let you tune for short explosive moves or longer sustained rallies.',
    signal: 'buy',
    enabled: true,
    threshold: 10,
    thresholdLabel: 'Min gain',
    thresholdMin: 1,
    thresholdMax: 100,
    thresholdStep: 1,
    thresholdSuffix: '%',
    threshold2: 5,
    threshold2Label: 'Over period',
    threshold2Min: 1,
    threshold2Max: 60,
    threshold2Step: 1,
    threshold2Suffix: ' days',
  },
  // ── Options: Put/Call Ratio ───────────────────────────────
  {
    id: 'put_call_ratio_low',
    name: 'Low Put/Call Ratio',
    description: 'PCR (Put/Call Ratio) measures the volume of put options traded versus call options. Puts give the right to sell a stock (typically bought as protection or bearish bets); calls give the right to buy (typically bullish bets). A low PCR below 0.7 means significantly more calls than puts are being traded, indicating that options market participants are positioned bullishly. Requires a Tradier API key.',
    signal: 'buy' as const,
    enabled: false,
    threshold: 0.7,
    thresholdLabel: 'PCR below',
    thresholdMin: 0.3,
    thresholdMax: 1.0,
    thresholdStep: 0.05,
  },
  {
    id: 'put_call_ratio_high',
    name: 'High Put/Call Ratio',
    description: 'A high PCR (Put/Call Ratio) above 1.0 means more put options are being traded than calls, indicating that options participants are predominantly hedging or betting on a price decline. A ratio above 1.2–1.5 is considered notably bearish sentiment in the options market. Requires a Tradier API key.',
    signal: 'sell' as const,
    enabled: false,
    threshold: 1.0,
    thresholdLabel: 'PCR above',
    thresholdMin: 0.7,
    thresholdMax: 2.0,
    thresholdStep: 0.05,
  },
  // ── Options: High IV ──────────────────────────────────────
  {
    id: 'high_iv',
    name: 'High Implied Volatility',
    description: 'IV (Implied Volatility) is derived from options prices and reflects the market\'s expectation of how much a stock will move in the future. IV Rank compares the current IV level to its range over the past year — a rank of 60% means IV is in the top 40% of its yearly range. High IV Rank signals that the options market is pricing in an unusually large move, often ahead of earnings, news events, or during periods of heightened uncertainty. Requires a Tradier API key.',
    signal: 'buy' as const,
    enabled: false,
    threshold: 60,
    thresholdLabel: 'IV Rank above',
    thresholdMin: 30,
    thresholdMax: 95,
    thresholdStep: 5,
    thresholdSuffix: '%',
  },
  // ── Options: Near Max Pain ────────────────────────────────
  {
    id: 'near_max_pain',
    name: 'Near Max Pain',
    description: 'Max Pain is the options strike price at which the total value of all outstanding options contracts (puts and calls) would expire worthless — resulting in the maximum financial loss for options buyers. The theory is that market makers, who are short those options, have an incentive to keep the price near this level into expiry. When the stock price is close to max pain, there is a gravitational pull toward that level as expiry approaches. Requires a Tradier API key.',
    signal: 'buy' as const,
    enabled: false,
    threshold: 3,
    thresholdLabel: 'Within',
    thresholdMin: 1,
    thresholdMax: 10,
    thresholdStep: 0.5,
    thresholdSuffix: '% of max pain',
  },
];
